# The URL the site will be built for
base_url = "https://illef.github.io"

title = "illef blog"
theme="plain"
author="illef"

generate_feeds = true
feed_filenames = ["feed.xml"]

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
[markdown]
highlight_code = true
highlight_theme = "ayu-light"
bottom_footnotes = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true


[extra]
# Put all your custom variables here

[link_checker]
internal_level = "error"
