# fly.toml app configuration file generated for remark42-muddy-bird-1812 on 2025-01-24T17:26:01+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'remark42-muddy-bird-1812'
primary_region = 'nrt'

[build]
  image = 'umputun/remark42:latest'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[mounts]]
  source = 'remark42_data_01'
  destination = '/srv/var'

[[vm]]
  size = 'shared-cpu-1x'
